// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDSGdvF7J3E-J92CiFygwhC8FNEhcGPos',
    appId: '1:265223126593:web:74b482e6c71e2113ecd0c0',
    messagingSenderId: '265223126593',
    projectId: 'mobile-camera-ab037',
    authDomain: 'mobile-camera-ab037.firebaseapp.com',
    storageBucket: 'mobile-camera-ab037.appspot.com',  
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZK2tcfXTdukeEI5HGJnWN4I2TMeqcn7M',
    appId: '1:265223126593:android:99110266466ba65cecd0c0',
    messagingSenderId: '265223126593',
    projectId: 'mobile-camera-ab037',
    storageBucket: 'mobile-camera-ab037.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBftj11tmRLE1JLfcEIWzHFHL9l40n23vk',
    appId: '1:265223126593:ios:f0f98e9b9e0af72decd0c0',
    messagingSenderId: '265223126593',
    projectId: 'mobile-camera-ab037',
    storageBucket: 'mobile-camera-ab037.appspot.com',
    iosClientId: '265223126593-vqq8luk9r3io1tl31jene9hqchr78bh3.apps.googleusercontent.com',
    iosBundleId: 'com.example.exampleFb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBftj11tmRLE1JLfcEIWzHFHL9l40n23vk',
    appId: '1:265223126593:ios:1f75c12141345071ecd0c0',
    messagingSenderId: '265223126593',
    projectId: 'mobile-camera-ab037',
    storageBucket: 'mobile-camera-ab037.appspot.com',
    iosClientId: '265223126593-9q8bj51kad9bsgi4vt3d0ef17geecfvk.apps.googleusercontent.com',
    iosBundleId: 'com.example.exampleFb.RunnerTests',
  );

  
}
